const router = require('express').Router();
const { authMiddleware } = require('../middleware/auth');
const c = require('../controllers/boardController');
router.get('/',              authMiddleware, c.getAllBoards);
router.post('/',             authMiddleware, c.createBoard);
router.get('/:id',           authMiddleware, c.getBoardById);
router.put('/:id',           authMiddleware, c.updateBoard);
router.delete('/:id',        authMiddleware, c.deleteBoard);
router.get('/:id/members',   authMiddleware, c.getBoardMembers);
router.get('/:id/cards/search', authMiddleware, c.searchCards);
router.get('/:id/cards/filter', authMiddleware, c.filterCards);
const lc = require('../controllers/labelController');
router.get('/:id/labels',         authMiddleware, lc.getBoardLabels);
router.post('/:id/labels',        authMiddleware, lc.createLabel);
module.exports = router;
